name: Set Commit Author and Push with SSH
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  set-author:
    runs-on: ubuntu-latest
    if: github.event.pusher.name != 'mankeli-contact'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Necessary to pull all history for rewriting

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set commit author
        run: |
          git config user.name "mankeli-contact"
          git config user.email "contact@mankeli.co"
          git commit --amend --no-edit --author="mankeli-contact <contact@mankeli.co>"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ssh: true
          force: true
